### ISSUE TITLE
Fix DsmTimerView list item name style

### ISSUE THREAD

**Issue by yugoccp** [yugoccp/yoda-scrum#1]
At DsmTimerView, `List.Item.Meta` doesn't fit well for list item content. Change the component with properly styled `List.Item` content.
- Each list item should display: avatar | name | timeInMs
- Highlight current member
- Display current member at the top of the list

**Comment by barceloscbc** [comment]
Hi @yugoccp! I will work on this issue :)

**Comment by yugoccp** [comment]
Thanks @barceloscbc :)
