### ISSUE TITLE
Adjust layout for larger screens

### ISSUE THREAD

**Issue by yugoccp** [yugoccp/yoda-scrum#14]
Adjust Views layouts to become friendly on larger screens.

**Comment by victorvilaca** [comment]
I'll work on this one.

**Comment by gargshruti30** [comment]
@yugoccp Can I work on this issue ?

**Comment by yugoccp** [comment]
@gargshruti30 I think @victorvilaca is already working on it, but feel free to join forces to resolve issue if you want :)
