### ISSUE TITLE
Make DsmTimerView timeout configurable

### ISSUE THREAD

**Issue by yugoccp** [yugoccp/yoda-scrum#2]
Actually DsmTimerView timeout value is fixed. We should add option to make timeout configurable.

- Add timeout input at DsmRoomView form.
- Add send timeout button.
- At server, update the timeout value and emit to all connected users.

**Comment by mskuybeda** [comment]
I am interested. Would you mind if I give try?

**Comment by yugoccp** [comment]
Of course @mskuybeda! :)

**Comment by yugoccp** [comment]
> I am interested. Would you mind if I give try?

**Comment by yugoccp** [comment]
@mskuybeda I misconfigured project settings, please ignore collaborator request and create PR for this issue :)
